.github/workflows/lint.yml, .github/workflows/test.yml, .golangci.yml, README.md, agent/agent_simple.go, commands/api.go, commands/vehicle.go, commands/vehicle_test.go, go.mod, go.sum, main.go, service/app.go
This includes UDS commands and various PIDs. 
One of the objectives here is not to rely on autopi / hardware impl to parse VIN out of the hex, so this also adds a method to extractVIN, has unit test. 
Original idea for trying different PIDs credit goes to @Khalaro from test script in python.
=> PLA-1230 Try different VIN commands untill one works

README.md, agent/agent_simple.go, commands/api.go, commands/vehicle.go, main.go
Adds new Bluetooth characteristic to the vehicle service to get the protocol used when getting VIN. Either returns 06 or 07
=> PLA-1233 get protocol used to decode VIN

go.mod, go.sum, main.go, scan_vin.go
- call our existing code to get the VIN in a variety of ways, including citroen can bus scan
- exits immediately after obtaining VIN.
=> PLA-1395 CLI command impl to get vin

main.go
do not start bluetooth app if 5.2 hw revision recognized.
=> Check for 5.2 hw revision to not start BLE

internal/logger.go, internal/logger_test.go, internal/network/data_sender.go, internal/network/mocks/data_sender_mock.go, main.go, scan_vin.go
- various refactors
- send power status with error mqtt
- bump to 5 number of max failed retries
=> PRO-1485 refactor and send additional info with errros

go.mod, go.sum, internal/logger.go, internal/logger_test.go, internal/loggers/logger_settings.go, internal/network/data_sender.go, internal/network/mocks/data_sender_mock.go, scan_vin.go
- use cloud event for message
- two custom extension headers
- refactor data sender, simplify usage and fix weird dependency
=> PRO-1555 Change payload to be a cloud event and refactor data sender

main.go
=> PRO-1591 add lastDTC

internal/fingerprint.go, internal/fingerprint_test.go, internal/models/network.go, internal/network/data_sender.go, internal/worker_runner.go, internal/worker_runner_test.go
- updated Cloud Event format according to [Thread](https://discord.com/channels/892438668453740634/1214658330581012480)
=> SM-647: Update Cloud Event format to team agreement

commands/vehicle.go, internal/loggers/template_store.go, internal/worker_runner.go, internal/worker_runner_test.go, service/app_test.go
- concurrently query obd and non obd signals
- added tests
=> SM-636: Implement support for intervals for querying and sending signals

commands/transactions.go, commands/vehicle.go, commands/vehicle_test.go, internal/api/api.go, internal/gateways/vehicle_signal_decoding.go, internal/loggers/pid_logger.go, internal/loggers/vin_logger.go, internal/models/template_configs.go, internal/queue/disk_storage_queue.go, internal/queue/memory_storage_queue.go, internal/queue/message.go, internal/queue/storage_queue.go, internal/vehicle_template.go, internal/worker_runner.go, internal/worker_runner_test.go
- added support for  CanflowControlClear and CanFlowControlIDPair
- added formula to cmd if type == python
=> SM-704: Support more obd.query options

internal/models/network.go, internal/network/data_sender.go, internal/network/mocks/data_sender_mock.go, internal/worker_runner.go, internal/worker_runner_test.go
- changed DeviceStatusData payload by adding wifi and location to the signals array
- created separate payload for the network data
=> SM-735: Modify edge-network status payload Part2

internal/models/network.go, internal/network/data_sender.go, internal/network/mocks/data_sender_mock.go, internal/worker_runner.go, internal/worker_runner_test.go
- added option to gzip Payload and send it over MQTT
- refactored code
=> SM-706: Compress payload on send status, decompress on benthos ingest

internal/gateways/mocks/identity_api_mock.go, internal/loggers/mocks/template_store_mock.go, internal/loggers/template_store.go, internal/worker_runner_test.go, main.go
- persist vehicle-info on disk
=> SM-754: write token id on disk

internal/network/data_sender.go
- updated specVersion for status and network payloads
=> SM-760: updated specVersion for status and network payloads

commands/device.go, commands/vehicle_test.go, internal/api/api.go, internal/loggers/passive_can_dumper.go, internal/models/network.go, internal/network/data_sender.go, internal/worker_runner.go, main.go, scan_vin.go
- added version, imei and UnitId to device object
=> SM-762: added version, imei and UnitId to device object

internal/network/data_sender.go, main.go
- send serial along with device errors
- retry on get ether Address
=> SM-812: send serial along with device errors

.idea/edge-network.iml, .idea/vcs.xml, internal/models/template_configs_test.go
adding these tests just for coverage,
turns out problem was in backend
=> SM-822 more formula related tests

internal/models/template_configs.go, internal/worker_runner.go, internal/worker_runner_test.go
- changed frequency of sending device status from 20 sec to 10
- send location every configurable x sec
=> SM-686: send location every configurable x

certificate/certificate.go, config-dev.yaml, config.yaml, config/config.go, internal/network/data_sender.go, internal/network/data_sender_test.go, main.go
=> SM-826: switch dev devices  to emqx

internal/worker_runner.go, internal/worker_runner_test.go
-if we failed too many times, we should send an error to the cloud
=> SM-823: if obd.query fails, it keeps retrying that one too many times

certificate/certificate.go, internal/loghooks.go, main.go
- disable certificate exchange flow for the prod env
=> SM-876: Disable certificate exchange flow for prod

ble_chars.go, certificate/certificate.go, certificate/certificate_test.go, commands/vehicle_test.go, config/config.go, internal/gateways/identity_api.go, internal/gateways/vehicle_signal_decoding.go, internal/loggers/mocks/template_store_mock.go, internal/loggers/passive_can_dumper.go, internal/loggers/template_store.go, internal/loggers/vin_logger.go, internal/models/network.go, internal/network/data_sender.go, internal/network/data_sender_test.go
- doing this since this most likely indicates a new pairing
- report some things to edge logs as necessary
=> SM-637 delete all settings when get VIN over BLE

internal/loghooks.go, internal/worker_runner.go, internal/worker_runner_test.go, main.go
=> SM-885:  Reduce logging when can't get GPS info(Hook Version)

internal/loghooks.go, internal/models/network.go, internal/network/data_sender.go, internal/worker_runner.go, internal/worker_runner_test.go
- added TokenId to errors payload
- improved logging with options
=> SM-884: tweak edge-logs - add software version, tokenId, batteryVoltage, more

internal/loggers/passive_can_dumper.go, internal/models/network.go, internal/network/data_sender.go, internal/network/mocks/data_sender_mock.go, main.go, scan_vin.go
=> SM-937: model slug to errors

internal/gateways/mocks/vehicle_signal_decoding_mock.go, internal/gateways/retry.go, internal/gateways/vehicle_signal_decoding.go, internal/loggers/dbc_passive_logger.go, internal/models/template_configs.go, internal/vehicle_template.go, main.go
- add UpdateDeviceConfigStatus on success download device template
=> SM-949: Update edge-network client to patch device status with a downloaded template

ble_chars.go, internal/fingerprint.go, internal/hooks/loghooks.go, internal/loggers/dbc_passive_logger.go, internal/network/data_sender.go, internal/network/data_sender_test.go, internal/worker_runner.go, internal/worker_runner_test.go, main.go
=> Test moving loghooks

internal/loggers/dbc_formula_decoder.go, internal/loggers/dbc_formula_decoder_test.go, internal/loggers/dbc_passive_logger.go
better handle the dbc formula parsing for passive scanning
=> better dbc formula handling

internal/worker_runner.go, internal/worker_runner_test.go
- filter out WiFi signal if wifi disconnected
=> SM-984: filter out wifi disconnected

config-dev.yaml, config.yaml, internal/network/data_sender.go, main.go
- enabled mqtt cert exchange and offline buffering to prod
=> SM-1027: Enable certificate exchange for prod and enable offline buffering for prod

config-dev.yaml, config.yaml, internal/network/data_sender.go, main.go
- enabled debug logs and fix the port
=> SM-1027: testing on prod device with mqtt buffering

internal/network/data_sender.go, main.go
=> SM-1027: disable debug logs

config-dev.yaml, config.yaml, config/config.go, internal/network/data_sender.go
- extract mqtt client buffering related configuration
=> SM-1021: Implement eviction strategy for fileStore

certificate/certificate.go, config-dev.yaml, config.yaml, config/config.go, internal/gateways/identity_api.go, internal/network/mqtt_store.go, internal/util/retry.go, internal/vehicle_template.go, main.go
- download config which has secrets from cloudflare workers
=> SM-845: Create Worker for returning configuration.

README.md, certificate/certificate.go, config-dev.yaml, config.yaml, config/config.go, internal/gateways/identity_api.go, internal/hooks/loghooks.go, internal/loggers/dbc_passive_logger.go, internal/network/data_sender.go, internal/network/data_sender_test.go, internal/network/mqtt_store.go, internal/util/retry.go, internal/vehicle_template.go, main.go
=> Mqtt to main

.github/workflows/lint.yml, internal/worker_runner.go, internal/worker_runner_test.go
- if no signals obtained, do not send a status payload
=> SM-1075: edge-network empty signals and error to edge-logs

ble_chars.go, can_dump_v2.go, certificate/certificate_test.go, dbc_scan.go, internal/hooks/loghooks.go, internal/loggers/dbc_passive_logger.go, internal/worker_runner.go, internal/worker_runner_test.go, main.go, scan_vin.go
- refactor loghooks.go by remove LogHook hook
- reduce number of failed gps location errors and pid queries errors
=> INTG-1334: less logs
